cave/urlshortener/apps/main/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (HomeView, URLRedirectView)

app_name = "main"

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='homeview'),
    url(r'^(?P<shortcode>[\w-]+)/$', URLRedirectView.as_view(), name='scode'),
 ]

cave/urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include('urlshortener.apps.main.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cave/urlshortener/apps/main/models.py
from django.conf import settings
from django.db import models
from django_hosts.resolvers import reverse
# from django.urls import reverse
from .utils import code_generator, create_shortcode
from .validators import validate_url, validate_dot_com

# SHORTCODE_MAX = settings.SHORTCODE_MAX
SHORTCODE_MAX = getattr(settings, 'SHORTCODE_MAX', 15)


class AcadeURLManager(models.Manager):
    def all(self, *args, **kwargs):
        qs_main = super(AcadeURLManager, self).all(*args, **kwargs)
        qs = qs_main.filter(active=True)
        return qs
    # function made to change all the shortcodes at the same time.
    def refresh_shortcodes(self):
        qs = AcadeURL.objects.filter(id__gte=1)
        new_codes = 0
        for q in qs:
            print("qq", q)
            q.shortcode = create_shortcode(q)
            print('q.shortcode :', q.shortcode)
            q.save()
            new_codes += 1
        return "New codes made:  {i}".format(i=new_codes)


class AcadeURL(models.Model):
    url = models.CharField(max_length=300, validators=[validate_url, validate_dot_com])
    shortcode = models.CharField(max_length=SHORTCODE_MAX, unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    objects = AcadeURLManager()

    # The keyword arguments are the names of the fields you’ve defined on your model.
    # The save method is an inherited method from models.Model which is executed to save an instance into a particular Model. Whenever one tries to create an instance of a model either from admin interface or django shell, save() function is run.
    # We can override save function before storing the data in the database to apply some constraint or fill some ready only fields like SlugField.
    def save(self, *args, **kwargs):
        if self.shortcode is None or self.shortcode == "":
            self.shortcode = create_shortcode(self)
            if not "http" in self.url:
                self.url = 'http://' + self.url
        super(AcadeURL, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.url)

    def get_short_url(self):
        url_path = reverse("main:scode", kwargs={"shortcode": self.shortcode}, host='www', scheme='http')
        return url_path

cave/urlshortener/apps/main/forms.py
from django import forms
from .validators import validate_url, validate_dot_com


class SubmitUrlForm(forms.Form):
    url = forms.CharField(label='Enter the Link here',  validators=[validate_url, validate_dot_com])

cave/urlshortener/apps/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import View
import requests
from django.http import JsonResponse
from .models import AcadeURL
from ..analytics.models import ClickEvent
from .forms import SubmitUrlForm
import pyshorteners


class HomeView(View):
    def get(self, request, *args, **kwargs):
        form = SubmitUrlForm()
        context = {
            "form": form
        }
        return render(request, 'main/index.html', context)

    def post(self, request, *args, **kwargs):
        form = SubmitUrlForm(request.POST)
        context = {
                'form': form
            }
        if form.is_valid():
            new_url = form.cleaned_data.get("url")
            obj, created = AcadeURL.objects.get_or_create(url=new_url)
            context = {
                "object": obj,
                "created": created,
                'form': SubmitUrlForm()
            }
        return render(request, 'main/index.html', context)


class URLRedirectView(View):
    def get(self, request, shortcode=None, *args, **kwargs):
        qs = AcadeURL.objects.filter(shortcode__iexact=shortcode)
        if qs.exists() and qs.count() == 1:
            obj = qs.first()
        obj = get_object_or_404(AcadeURL, shortcode=shortcode)
        ClickEvent.objects.create_event(obj)
        return HttpResponseRedirect(obj.url)


# class HomeView(View):
#     def get(self, request, *args, **kwargs):
#         form = SubmitUrlForm()
#         context = {
#             "form": form
#         }
#         # full_link = request.get('full_link')
#         # print("going through : ", full_link)
#         return render(request, 'main/index.html', context)
#
#     def post(self, request, *args, **kwargs):
#         print(request.POST)
#         print(request.POST.get('url'))
#         form = SubmitUrlForm(request.POST)
#         context = {
#             "title": "shortener.co",
#             "form": form
#         }
#         template = 'main/index.html'
#         # print("before", form.cleaned_data)
#         if form.is_valid():
#             print("after", form.cleaned_data)
#             new_url = form.cleaned_data.get("url")
#             obj, created = AcadeURL.objects.get_or_create(url=new_url)
#             context = {
#                 "object": obj,
#                 "created": created,
#             }
#             if created:
#                 template = 'main/success.html'
#             else:
#                 template = 'main/already_exists.html'
#             # print(obj.get_short_url())
#         # print("going through : ", full_link)
#         return render(request, template, context)


# def acade_redirect_view(request, shortcode=None, *args, **kwargs):
    # print(request.user)
    # print(request.user.is_authenticated)
    # print(args)
    # print(kwargs)
    # obj = AcadeURL.objects.get(shortcode=shortcode)

    # try:
    #     obj = AcadeURL.objects.get(shortcode=shortcode)
    # except Exception as ex:
    #     obj = AcadeURL.objects.all().first()

    # obj_url = None
    # qs = AcadeURL.objects.filter(shortcode__iexact=shortcode)
    # if qs.exists() and qs.count() == 1:
    #     obj = qs.first()
    #     obj_url = obj.url
    # obj = get_object_or_404(AcadeURL, shortcode=shortcode)
    # print('a== ', shortcode)
    # return HttpResponseRedirect(obj.url)
    # return HttpResponse("hello {sc}".format(sc=obj.url))

# def urlshortener(request):
#     if request.method == 'POST':
#         full_link = request.POST.get('full_link')
#         full_link = full_link.strip()
#         print(full_link)
#         headers = {
#             'Authorization': 'Bearer f5800c2a76a863ebea40f5d7c0225a39f67cd301',
#             'Content-Type': 'application/json',
#         }
#         data = '{ "long_url": "'+full_link+'" }'
#         response = requests.post('https://api-ssl.bitly.com/v4/shorten', headers=headers, data=data)
#         # print(response.json())
#         sl = response.json().get('link')
#         ll = response.json().get('long_url')
#         rr = {'shorturl': sl, 'longurl': ll}
#     return JsonResponse(rr)



# def urlshortener(request):
#     if request.method == 'POST':
#         full_link = request.POST.get('full_link')
#         print(full_link)
#         API_KEY = "2102250082883d42e106dfad1f039085adb64"
#         # API_KEY = "0f6c7489c714438a8fc272e7a2cd13ed"
#         BASE_URL = "https://cutt.ly/api/api.php"
#         pay_load = {"key": API_KEY, "short": full_link, "name": ""}
#         request = requests.get(BASE_URL, params=pay_load)
#         data = request.json()
#         print(data)
#         rr = {'status': 'ok.', 'data': data}
#     return JsonResponse(rr)

# ACCESS_TOKEN = 'f5800c2a76a863ebea40f5d7c0225a39f67cd301'

# def urlshortener(request):
#     if request.method == 'POST':
#         full_link = request.POST.get('full_link')
#         full_link = full_link.strip()
#         print("going through : ", full_link)
#         rr = {}
#     return JsonResponse(rr)

cave/urlshortener/apps/main/templates/main/already_exists.html
{% load static %}
<div style="align-text: center; width:800px; margin:0 auto;">
    <h1>Already Exists</h1>
    <p>{{ object.url}}</p>
    {% if object.clickevent %}<p>Count : {{ object.clickevent.count }}</p>{% endif %}
    <p><a href='{{object.get_short_url }}'>{{ object.get_short_url }}</a></p>
    <a href="/">+ New</a>
</div>

cave/urlshortener/apps/main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <!-- Box icons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <title>Acade | Url Shortener</title>
  </head>
  <body>
    <main>
      <header>
        <a href="/" class="logo pink-blue-gradient-text">Acade</a>
        <div class="cta">
          <a href="#" class="btn btn-login">
            <span>Login</span>
          </a>
          <a href="#" class="btn btn-register">
            <span>Register</span>
          </a>
        </div>
      </header>
      <div class="container">
        <div class="hero-section">
          <h2 class="section-title">
            <span class="blue-pink-gradient-text">Shorten</span>
            <span class="pink-blue-gradient-text">Your</span>
            <span class="pink-blue-gradient-text">Loooong Links :)</span>
          </h2>
          <p class="section-desc">
            Acade is an efficient and easy-to-use URL shortening service that
            streamlines your online experience.
          </p>
          <form method="POST" action=""> {% csrf_token %}
            <div class="icon">
              <i class="bx bx-link"></i>
            </div>
            {{form}}
            <button  onclick="remove_input_value(event)"  type="submit">Shorten Url!</button>
          </form>
          <div class="dashboard">
            <table>
              <thead>
                <th>Short Url</th>
                <th>Long Url</th>
                <th>Actions</th>
              </thead>
              <tbody>
                <tr>
                  <td id="shortUrl">
                    {% if object.get_short_url %}
                    <a href="{{ object.get_short_url }}" target="_blank">{{ object.get_short_url }}</a>
                    {% else %}
                    <a href="http://www.acade.com:8000/nz01e4/" target="_blank">http://www.acade.com:8000/nz01e4/</a>
                    {% endif %}
                  </td>
                  <td id="longUrl">{% if object.url %}{{ object.url}}{% else %}https://www.desishub.com/{% endif %}</td>
                  <td>
                    <div class="actions">
                      <button title="copy short url" id="copyBtn">
                        <div class="icon">
                          <i class="bx bxs-copy"></i>
                        </div>
                      </button>
                      <a href="#" title="delete">
                        <div class="icon delete">
                          <i class="bx bx-trash"></i>
                        </div>
                      </a>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="container">
        <footer>
          <p class="blue-pink-gradient-text">
            App Designed JB @ <a href="https://www.desishub.com">desishub</a>
          </p>
          <p class="pink-blue-gradient-text">
            Backend implemented by @
            <a href="https://www.academycity.com">Academy City</a>
          </p>
        </footer>
      </div>
    </main>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

cave/urlshortener/apps/main/templates/main/index_.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="{% static 'js/js.cookie.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous">
</script>
    <!-- Box icons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <title>Bitly | Url Shortener</title>
  </head>
  <body>
    <main>
      <header>
        <a href="/" class="logo pink-blue-gradient-text">Bitly</a>
        <div class="cta">
          <a href="#" class="btn btn-login">
            <span>Login</span>
          </a>
          <a href="#" class="btn btn-register">
            <span>Register</span>
          </a>
        </div>
      </header>
      <div class="container">
        <div class="hero-section">
          <h2 class="section-title">
            <span class="blue-pink-gradient-text">Shorten</span>
            <span class="pink-blue-gradient-text">Your</span>
            <span class="pink-blue-gradient-text">Loooong Links :)</span>
          </h2>
          <p class="section-desc">
            Bitly is an efficient and easy-to-use URL shortening service that
            streamlines your online experience.
          </p>
          <div class="form_" method="post">
            <div class="icon">
              <i class="bx bx-link"></i>
            </div>
           <input
              type="text"
              id="inputLink"
              name="input-link"
              placeholder="Enter the Link here"
            />
            <button class="" onclick="shorten_url(event)" type="submit">Shorten Url!</button>
          </div>
          <div class="dashboard">
            <table>
              <thead>
                <th>Short Url</th>
                <th>Long Url</th>
                <th>Actions</th>
              </thead>
              <tbody>
                <tr id="tr_">
                  <td id="shortUrl" style="visibility:hidden"></td>
                  <td id="longUrl" style="visibility:hidden"></td>
                  <td>
                    <div class="actions">
                      <button title="copy short url"  style="visibility:hidden">
                        <div class="icon" id="copyBtn">
                          <i class="bx bxs-copy"></i>
                        </div>
                      </button>
                      <button style="visibility:hidden">
                      <a href="#" title="delete" >
                        <div class="icon delete" id="deleteBtn">
                          <i class="bx bx-trash"></i>
                        </div>
                      </a>
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="container">
        <footer>
          <p class="blue-pink-gradient-text">
            App Designed JB @ <a href="https://www.desishub.com">desishub</a>
          </p>
          <p class="pink-blue-gradient-text">
            Backend implemented by @
            <a href="https://www.academycity.com">Academy City</a>
          </p>
        </footer>
      </div>
    </main>
    <script src="{% static 'js/app.js' %}"></script>

    <script type="text/javaScript">
        var csrftoken = Cookies.get('csrftoken');
          function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          }
          $.ajaxSetup({
            beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
            }
          });
          var link_urlshortener = '{% url "main:homeview" %}'
          function shorten_url(event)
          {
            var full_link_ = document.getElementById("inputLink").value
            alert(full_link_)
            if(full_link_==""){alert("Enter link");return;}
             try{
                  $.post(link_urlshortener,
                    {
                      full_link : full_link_,
                    },
                    function(data){
                        //alert(JSON.stringify(data))
                        short_url = data['shorturl']
                        long_url = data['longurl']
                        document.getElementById("shortUrl").innerHTML = short_url
                        document.getElementById("longUrl").innerHTML = long_url
                        document.getElementById("shortUrl").style.visibility = "visible"
                        document.getElementById("longUrl").style.visibility = "visible"
                        document.getElementById("copyBtn").style.visibility = "visible"
                        document.getElementById("deleteBtn").style.visibility = "visible"
                        document.getElementById("inputLink").value = ""

                        var cbtn =  document.getElementById("copyBtn")
                        var dbtn = document.getElementById("deleteBtn")
                       if(dbtn.innerHTML==""){dbtn.innerHTML='<i class="bx bx-trash"></i>'; cbtn.innerHTML='<i class="bx bxs-copy"></i>'}

                        document.getElementById("deleteBtn").onclick = function(event)
                        {
                         document.getElementById("shortUrl").innerHTML = ""
                         document.getElementById("longUrl").innerHTML = ""
                         document.getElementById("copyBtn").innerHTML = ""
                         document.getElementById("deleteBtn").innerHTML = ""
                        }
                    });
             }catch(er){alert(er)}

          }
    </script>
  </body>
</html>

cave/urlshortener/apps/main/templates/main/success.html
<div style="align-text: center; width:800px; margin:0 auto;">
    <h1>Successfully Created</h1>
    <p>{{ object.url}}</p>
    <p>Count : {{ object.clickevent.count }}</p>
    <p><a href="{{ object.get_short_url }}">{{ object.get_short_url }}</a></p>

    <a href="/">+ New</a>
</div>